---
title: "lab04_mengran"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

mydat <- read.csv("C:/Users/mgao05/Desktop/PAI INdenpendent study/pai730/quiz2/NhoodValPerAcreByDecade.csv", header= TRUE)
library( dplyr )
library(maptools)
library(sp)
library(dplyr)
library(maps)
library( markdown )
library(pander)

setwd("C:/Users/mgao05/Desktop/PAI INdenpendent study/week 3-4/01-05-2015/")
syr.parcel <- readShapePoly(fn="01-05-2015", proj4string=CRS("+proj=longlat +datum=WGS84") )
plot( syr.parcel, border="gray10")

head( as.data.frame( syr.parcel ) )

syr.dat <- as.data.frame( syr.parcel )

names( syr.dat )

nrow( syr.dat )



```



```{r}
# Question 1: How many single family homes are in each neighborhood?
# Create a table of the count of single family homes by neighborhood
# Highlight all single family homes, using a different color for each neighborhood



list.by.neighborhood <- table( syr.dat$Nhood[syr.dat$LandUse == "Single Family"])

list.by.neighborhood


col.Nhood <- c(  "darkorchid1", "mediumorchid2", "magenta3", "darkmagenta",
                "yellow1", "lightgoldenrod1", "lightpink", "hotpink", "deeppink", "violetred3", "indianred", "firebrick",
                "darkslategray2", "lightblue3", "dodgerblue", "royalblue2", "deepskyblue4", 
                "lightsalmon1", "darkorange", "chocolate1", "orange3", "orangered2",
                "mediumpurple1","gold", "goldenrod", "darkgoldenrod1",
                "chartreuse2", "darkolivegreen3", "darkseagreen3", "green4", "seagreen4",
                "gray40", "gray" )

palette(col.Nhood)

Nhood.Color <- factor(syr.dat$Nhood)
Nhood.Color[syr.dat$LandUse != "Single Family"] <- NA



graphics.off() 
par("mar") 
par(mar=c(1,1,1,1))

plot(syr.parcel, border="grey95", col=Nhood.Color, main="Single Family Homes By Neighborhood")

legend("bottomright", bg="white", pch=19, pt.cex=0.8, cex=0.4, legend=levels(syr.parcel$Nhood), col=col.Nhood)




```



```{r}
# Question 2: Where does land in Syracuse have the highest value? 
# Create a table of the count of single family homes with values above $200k in each neighborhood, as a pecentage of all single family homes
# Plot the value / acre of all parcels in Syracuse


#table of count of single family homes above $200k in each neighborhood

highvalue.single <- table( syr.dat$Nhood[syr.dat$LandUse == "Single Family" &   
                           syr.dat$AssessedVa > 200000]
                         ) 

highvalue.single

#percentage of expensive single family housing

tbl.expensive <- highvalue.single

percentage.table <- cbind(tbl.expensive,prop.table(tbl.expensive))




#plot value/acre of all parcels in Syracuse

value.acre <- mutate(.data = syr.dat, value.per.acre = AssessedLa / Acres)

value.acre2 <- value.acre[na.omit(value.acre$value.per.acre), ]
col.divide <- cut( value.acre$value.per.acre, breaks = 5 )

plot( syr.parcel, border="gray80", col=col.divide, oma=c(5,7,1,1) )


min.x <- tapply( value.acre$value.per.acre, col.divide, min )
max.x <- tapply( value.acre$value.per.acre, col.divide, max )

legend.text <- paste( min.x, max.x, sep=" to ")



legend( "bottomright", bg="white",
        pch=19, pt.cex=0.8, cex=0.6,
        legend=legend.text, 
        col=col.divide, 
        box.col="white",
        title="Land Value" 
)



##Problem!! still have NAs in legend category and the color difference didn't show up in plot and it is only purple

```



```{r}
# Question 3: What is the age of single family homes in each neighborhood? 
# Create a table that reports the 10th, 25th, 50th, 75th, and 90th percentile of home ages in each neighborhood.
#Create a choropleth map that shows the age of properties by decade, pre-1900s can be one category.


Nhood.YearBuilt <- select(syr.dat, Nhood, LandUse, YearBuilt)
Yearbuilt.single <- filter(Nhood.YearBuilt, LandUse == "Single Family" )

Yearbuilt.single$YearBuilt <- as.numeric(as.character((Yearbuilt.single$YearBuilt)))

Yearbuilt.age <- mutate(Yearbuilt.single, Age = 2017 - YearBuilt)

Yearbuilt.age <- select(Yearbuilt.age, Nhood, Age)

age.nbhd <- group_by(Yearbuilt.age, Nhood)

PercentileTable <- summarise(age.nbhd, Tenth = quantile(Age, probs=0.10, na.rm=T), TwentyFifth = quantile(Age, probs=0.25, na.rm=T), Fiftieth = quantile(Age, probs=0.50, na.rm=T), SeventyFifth = quantile(Age, probs=0.75, na.rm=T), Ninetieth = quantile(Age, probs=0.90, na.rm=T))
pander(PercentileTable)



#create a map shows age of properties by decade, pre-1900s can be one category

Map <- select(syr.dat, YearBuilt)
Map$YearBuilt <- as.numeric(as.character((Map$YearBuilt)))


color.function <- colorRampPalette( c("red","blue" )) 

col.ramp <- color.function( 13 ) # number of groups you desire

color.vector <- cut(Map$YearBuilt, breaks=c(1790, seq(from = 1900, to = 2020, by =10)), labels = col.ramp )  

color.vector <- as.character( color.vector )

plot(syr.parcel, col=color.vector, border=F, main="Age of Property by Decade")
#map.scale( metric=F, ratio=F, relwidth = 0.15, cex=0.5 )
legend.text <- c("1790-1900","1900-1910", "1910-1920", "1920-1930", "1930-1940", "1940-1950", "1950-1960", "1960-1970", "1970-1980", "1980-1990", "1990-2000", "2000-2010", "2010-2020")
legend( "bottomright", bg="white",
        pch=19, pt.cex=1.5, cex=0.7,
        legend=legend.text, 
        col=col.ramp, 
        box.col="white",
        title="Built Year of House")




```





